project:
  type: website
  output-dir: docs

website:
  title: "GENE 46100"
  navbar:
    left:
      - href: index.qmd
        text: Home
  body-footer: |
      © [HakyImLab and Listed Authors](https://hakyimlab.org) - [CC BY 4.0 License](https://creativecommons.org/licenses/by/4.0/)
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


